name: 'GTFO'
description: 'Get The F*** Out - Analyze and reclaim disk space on GitHub runners'
author: 'bfenski'

branding:
  icon: 'trash-2'
  color: 'red'

runs:
  using: 'composite'
  steps:
    - name: Disk usage overview (df -h)
      shell: bash
      run: |
        echo "============================================"
        echo "  GTFO - Disk Usage Analysis"
        echo "============================================"
        echo ""
        echo ">>> Filesystem usage (df -h)"
        echo "--------------------------------------------"
        df -h
        echo ""

    - name: Top-level directory sizes (du -sm /*)
      shell: bash
      run: |
        echo ">>> Top-level directory sizes (du -sm /*)"
        echo "--------------------------------------------"
        sudo du -sm /* 2>/dev/null | sort -rn | head -20 || true
        echo ""

    - name: Largest directories in /usr
      shell: bash
      run: |
        echo ">>> Largest directories in /usr"
        echo "--------------------------------------------"
        sudo du -sm /usr/* 2>/dev/null | sort -rn | head -10 || true
        echo ""

    - name: Largest directories in /opt
      shell: bash
      run: |
        echo ">>> Largest directories in /opt (if exists)"
        echo "--------------------------------------------"
        sudo du -sm /opt/* 2>/dev/null | sort -rn | head -10 || echo "No /opt directory"
        echo ""

    - name: Largest directories in /home
      shell: bash
      run: |
        echo ">>> Largest directories in /home"
        echo "--------------------------------------------"
        sudo du -sm /home/* 2>/dev/null | sort -rn | head -10 || echo "No /home directory"
        echo ""

    - name: Contents of /mnt (secondary disk)
      shell: bash
      run: |
        echo ">>> Contents of /mnt (secondary disk)"
        echo "--------------------------------------------"
        if mountpoint -q /mnt 2>/dev/null; then
          echo "Device: $(df /mnt | tail -1 | awk '{print $1}')"
          echo "Total: $(df -h /mnt | tail -1 | awk '{print $2}')  Used: $(df -h /mnt | tail -1 | awk '{print $3}')  Free: $(df -h /mnt | tail -1 | awk '{print $4}')"
          echo ""
          echo "Contents:"
          sudo ls -la /mnt 2>/dev/null || true
          echo ""
          sudo du -sm /mnt/* 2>/dev/null | sort -rn | head -10 || true
        else
          echo "/mnt is not a separate mount point"
        fi
        echo ""

    - name: Docker images (if present)
      shell: bash
      run: |
        echo ">>> Docker images"
        echo "--------------------------------------------"
        if command -v docker &> /dev/null; then
          docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}" 2>/dev/null || echo "Docker not accessible"
        else
          echo "Docker not installed"
        fi
        echo ""

    - name: Swap and memory info
      shell: bash
      run: |
        echo ">>> Memory and swap"
        echo "--------------------------------------------"
        free -h 2>/dev/null || vm_stat
        echo ""

    - name: Summary
      shell: bash
      run: |
        echo "============================================"
        echo "  Summary - Potential bloat locations"
        echo "============================================"
        echo ""
        echo "Common bloat on GitHub runners:"
        echo "  - /usr/local/lib/android (~12GB)"
        echo "  - /usr/share/dotnet (~2GB)"
        echo "  - /opt/ghc (~2GB)"
        echo "  - /usr/local/share/boost (~1GB)"
        echo "  - /usr/share/swift (~1.5GB)"
        echo "  - Docker images (varies)"
        echo ""
        echo "Run 'sudo rm -rf <path>' to remove unwanted directories"
        echo "============================================"
